[
  {
    img: "https://example.com/image1.jpg",
    young_adult: true,
    identity: "",
    title: "The Shadow of the Wind",
    by_name: "Elena Waters",
    fiction: true,
    ratings: 4.7,
  },
  {
    img: "https://example.com/image2.jpg",
    young_adult: true,
    identity: "",
    title: "Sharp Objects",
    by_name: "Nathan Black",
    classic: true,
    ratings: 4.2,
  },
  {
    img: "https://example.com/image3.jpg",
    young_adult: true,
    identity: "",
    title: "The Night Circus",
    by_name: "Sophia Gray",
    classic: true,
    ratings: 4.5,
  },
  {
    img: "https://example.com/image4.jpg",
    young_adult: true,
    identity: "",
    title: "The Final Empire",
    by_name: "Marcus Evergreen",
    fiction: true,
    ratings: 4.8,
  },
  {
    img: "https://example.com/image5.jpg",
    young_adult: true,
    identity: "",
    title: "The Starlit Path",
    by_name: "Ava Rivers",
    fiction: true,
    ratings: 4.6,
  },
  {
    img: "https://example.com/image6.jpg",
    young_adult: true,
    identity: "",
    title: "The Storied Life of A.J. Fikry",
    by_name: "Daniel Summer",
    classic: true,
    ratings: 4.4,
  },
];
